export const layers=[{id:'services',name:'Public services',color:'#b97855'},{id:'resources',name:'Land & resources',color:'#738870'},{id:'participation',name:'Civic participation',color:'#ac995d'}];
export const records=[
{id:'mak',title:'A clearer route to water access',place:'Makueni County, Kenya',coords:[37.62,-1.8],layer:'services',theme:'Water & sanitation',description:'A community water point needs a clear maintenance contact. Connect the service question to the county water office and ask for a dated response.',source:'Makueni County Government',url:'https://makueni.go.ke/',date:'2026-09-19',holder:'County water services office',witness:'Community water committee',ask:'Who is responsible for this water point, and when can the community expect a maintenance update?'},
{id:'gha',title:'Follow the community benefit',place:'Tarkwa, Ghana',coords:[-1.99,5.3],layer:'resources',theme:'Community benefit',description:'Follow a community benefit question from a mining-affected locality to the district assembly. Ask where residents can inspect the allocation and next consultation.',source:'Ghana Minerals Commission',url:'https://www.mincom.gov.gh/',date:'2026-09-17',holder:'District assembly information desk',witness:'Community association',ask:'Where can residents view the community benefit allocation and the next public consultation date?'},
{id:'sen',title:'Make the next meeting accessible',place:'Dakar, Senegal',coords:[-17.45,14.69],layer:'participation',theme:'Citizen participation',description:'Request the date, venue and accessible participation arrangements for the next local meeting. Leave a paper route for people without a connection.',source:'Senegal public services portal',url:'https://www.servicepublic.gouv.sn/',date:'2026-09-16',holder:'Municipal public information desk',witness:'Local youth association',ask:'When is the next public meeting, and how can residents submit a question in advance?'},
{id:'nga',title:'Find the right service desk',place:'Abuja, Nigeria',coords:[7.49,9.06],layer:'services',theme:'Service accountability',description:'Turn a confusing service route into a written request for the right office, required documents and response time.',source:'SERVICOM Nigeria',url:'https://servicom.gov.ng/',date:'2026-09-20',holder:'Service improvement desk',witness:'Residents association',ask:'Which desk holds this service request, what documents are needed, and what is the expected response time?'},
{id:'drc',title:'Put a land question on record',place:'Kolwezi, DR Congo',coords:[25.47,-10.72],layer:'resources',theme:'Land & resources',description:'Request a public consultation record and a named institutional contact for a community land question. No household or person locations are collected.',source:'DRC Ministry of Mines',url:'https://mines.gouv.cd/',date:'2026-09-15',holder:'Provincial public information office',witness:'Community liaison group',ask:'Which public consultation record covers this area, and who can provide a written response to residents?'},
{id:'moz',title:'A place in the local conversation',place:'Maputo, Mozambique',coords:[32.57,-25.97],layer:'participation',theme:'Inclusive participation',description:'Ask for an inclusive way to contribute to a local civic meeting, including an offline option for residents without internet access.',source:'Mozambique Government',url:'https://www.portaldogoverno.gov.mz/',date:'2026-09-16',holder:'Municipal citizen service office',witness:'Women-led community group',ask:'How can residents contribute to the next civic meeting by paper or through a community representative?'},
{id:'zaf',title:'Know the next step for a request',place:'Johannesburg, South Africa',coords:[28.05,-26.2],layer:'services',theme:'Public services',description:'Attach a service query to a named municipal desk and request an acknowledgement with a reference number.',source:'City of Johannesburg',url:'https://www.joburg.org.za/',date:'2026-09-20',holder:'Municipal service centre',witness:'Ward community forum',ask:'Please acknowledge this service query, provide a reference number and confirm the next response date.'},
{id:'ken',title:'Connect a budget to a service',place:'Nairobi, Kenya',coords:[36.82,-1.29],layer:'participation',theme:'Budget participation',description:'Find the public-budget information desk and ask where residents can inspect a service allocation and give feedback.',source:'Kenya National Treasury',url:'https://www.treasury.go.ke/',date:'2026-09-18',holder:'Public participation information desk',witness:'Budget accountability group',ask:'Where is the published allocation for this service and how can residents submit feedback?'}];
export const seeds=[{id:'TRL-260918-104',record:'gha',title:'Follow the community benefit',holder:records[1].holder,witness:records[1].witness,due:'2026-09-25',created:'2026-09-18',answered:null,links:[]},{id:'TRL-260916-108',record:'sen',title:'Make the next meeting accessible',holder:records[2].holder,witness:records[2].witness,due:'2026-09-20',created:'2026-09-16',answered:'2026-09-19',links:[]}];
export const date=day=>`2026-09-${String(day).padStart(2,'0')}`;
export const short=d=>new Date(d+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short'});
export const find=id=>records.find(r=>r.id===id);
export const state=(f,today)=>f.created>today?'Not started':f.answered&&f.answered<=today?'Answered':(Date.parse(today)-Date.parse(f.due))/86400000>=7?'Expired unanswered':f.due<today?'Overdue':'Awaiting response';
export function load(){try{const x=JSON.parse(localStorage.getItem('trail-v3'));return Array.isArray(x)&&x.every(f=>f&&find(f.record)&&['id','title','holder','witness','due','created'].every(k=>typeof f[k]==='string')&&Array.isArray(f.links)&&f.links.every(find))?x:seeds}catch{return seeds}}
export function packet(f,format,today){const r=find(f.record);const head=`TRAIL · DEMONSTRATION FILE\n${f.id}\n${f.title}\n\nPlace: ${r.place}\nProposed holder (not accepted): ${f.holder}\nProposed witness: ${f.witness}\nRequested response date: ${f.due}\nState on ${today}: ${state(f,today)}\n`;
const body=format==='sms'?`\nMESSAGE FOR THE HOLDER\n${r.ask} Please reply by ${f.due}, quoting ${f.id}.\n\nCHECK-IN TEMPLATE\nSTATUS ${f.id}\n\nUSSD FLOW (prototype only)\nLocal civic service → Check a file → Enter receipt → Read holder, due date and state.\nNo live SMS number or USSD shortcode is provisioned. Do not dial or send this template.\n`:format==='radio'?`\nRADIO / MEETING SCRIPT\n“Residents of ${r.place}: we have a question about ${r.theme.toLowerCase()}. ${r.ask} Our proposed holder is ${f.holder}. Please provide a response by ${short(f.due)}. The proposed witness is ${f.witness}. To follow up, quote ${f.id} to the community meeting facilitator.”\n\nAdapt this script with a local-language speaker. Never broadcast affected individuals’ names. This is not a verified notice.\n`:`\n01 · CHECK THE SOURCE\nReview the source and limitations below. Verify locally before acting.\n\n02 · ASK THE HOLDER\n${r.ask}\n\n03 · TAKE TWO HANDS\nAsk the proposed holder to acknowledge the file and the proposed witness to retain a copy. No acceptance is implied.\n\n04 · FOLLOW THROUGH\nReturn by ${f.due}. Quote ${f.id}. Record a response, or follow up if overdue. Seven days after the requested date, this demo marks silence “Expired unanswered”, not resolved.\n\nRESPONSE / NOTES\n${f.answered?'Simulated holder acknowledgement; no real institutional response.':'_________________________________________________\n_________________________________________________'}\n`;
return head+body+`\nSOURCE & LIMITS\n${r.source} — ${r.url}\nSource class: public institutional portal\nListed: ${r.date} (demo timeline)\nContent fetched at: not fetched.\nLast independently verified: unknown.\nThe portal is a research starting point, not proof of this illustrative case.\n`+(f.links.length?`\nLINKED CONTEXT\n${f.links.map(id=>find(id).title+' — '+find(id).url).join('\n')}\n`:'')+'\nDEMO BOUNDARY\nNo sensitive or personal information. Proposed roles, not confirmed commitments. Saved in this browser only. No institutional delivery, real SMS or USSD. Requested dates are not legal deadlines.\n';}
